# .github/workflows/validacion.yml
name: Validación de HTML y CSS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Validar HTML & CSS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar validadores
      run: |
        npm install -g html-validator-cli css-validator

    - name: Validar HTML
      run: |
        html-validator --file=./index.html --verbose

    - name: Validar CSS
      run: |
        css-validator ./styles.css

